<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="nopCommerceSuite" duration-ms="11304" started-at="2019-04-18T02:29:30Z" finished-at="2019-04-18T02:29:42Z">
    <groups>
    </groups>
    <test name="chrometest" duration-ms="11304" started-at="2019-04-18T02:29:30Z" finished-at="2019-04-18T02:29:42Z">
      <class name="com.nopCommerce.TestCases.TC_LoginTest_001">
        <test-method status="PASS" signature="setUp(java.lang.String)[pri:0, instance:com.nopCommerce.TestCases.TC_LoginTest_001@548e7350]" name="setUp" is-config="true" duration-ms="2978" started-at="2019-04-18T02:29:31Z" finished-at="2019-04-18T02:29:34Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="loginTest()[pri:0, instance:com.nopCommerce.TestCases.TC_LoginTest_001@548e7350]" name="loginTest" duration-ms="8081" started-at="2019-04-18T02:29:34Z" finished-at="2019-04-18T02:29:42Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at com.nopCommerce.TestCases.TC_LoginTest_001.loginTest(TC_LoginTest_001.java:37)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.nopCommerce.TestCases.TC_LoginTest_001@548e7350]" name="tearDown" is-config="true" duration-ms="79" started-at="2019-04-18T02:29:42Z" finished-at="2019-04-18T02:29:42Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.nopCommerce.TestCases.TC_LoginTest_001 -->
    </test> <!-- chrometest -->
  </suite> <!-- nopCommerceSuite -->
</testng-results>
